macro(push variable_name)
  if(DEFINED ${variable_name})
    if(DEFINED _${variable_name})
      push(_${variable_name})
    endif()
    set(_${variable_name} "${${variable_name}}")
  endif()
endmacro()
